---
title: "SST-115 Introduction to Statistics"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

# Syllabus

Welcome to the course website for SST 115, Introduction to Statistics. To begin, you can find the course syllabus linked below:

- [Click here](syllabus115f24.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

[Mathlab Help Hours](mathlab_hours.pdf) 

# Course Materials

## Exam \#1 Content

### Week 1 (Intro)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Fri 8/30 | [Syllabus](syllabus115f24.html) | - | - |

**Assignments and Deadlines**: None

---

### Week 2 (R / Data Visualization)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/02 | [Introduction](lectures/00_introduction.pdf) | [In-class](labs/00_markdown.html) | IMS Sections 1.2.1-1.2.3 |
| Wed 9/04 | [Intro to R](lectures/01_R_introduction.pdf) | [Intro R Lab](labs/01_introR.html) [[solution]](labs/01_introR_solutions.html) | - |
| Fri 9/06 | [Data Visualization](lectures/02_DataVisualization.pdf) | Intro R cont'd | - |

**Assignments and Deadlines**

1) Install R (https://cran.r-project.org/)
2) Install RStudio (https://posit.co/download/rstudio-desktop/)
3) [Intro R Lab](labs/01_introR.html) due Wednesday 9/11 at 10pm. I only want to see the 3 questions from the lab in your submission file, not the entire text of the tutorial lab.

**Note:** Homework/Labs should be neatly formatted with questions specified as headers and with your R code and written solutions underneath. [Here is an example](homework/example_hw1.pdf) of how it should look (courtesy of Professor Nolte)

---

### Week 3 (Data Visualization)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/09 | [Data Visualization Part 2](lectures/03_DataVisualization_Part2.pdf) | [Data Viz](labs/DataVisualizationLab.html) and [Template](labs/DataVisualizationLab.Rmd) [[solution]](labs/DataVisualizationLab_Solutions.html)| - |
| Wed 9/11 | - | [ggplot lab](labs/ggplot2_lab.html) [[solution]](labs/ggplot_lab_solutions.html) | - |
| Fri 9/13 | - | [ggplot lab](labs/ggplot2_lab.html) [[solution]](labs/ggplot_lab_solutions.html) continued | - |

**Assignments and Deadlines**

1) [Intro R Lab](labs/01_introR.html) due Wednesday 9/11 at 10pm.
2) [Data Viz Lab](labs/DataVisualizationLab.html) due Wednesday 9/11 at 10pm.
3) [Homework 1](homework/Homework1.html) is assigned Monday 9/09 and will be due the following Monday 9/16 at 10pm. The R markdown file for writing your answers can be found [here](homework/Homework1.Rmd)
4) [ggplot lab](labs/ggplot2_lab.html) due Monday 9/16 at 10pm.

---

### Week 4 (Describing Data / Study Design)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/16 | [Numerical Summaries](lectures/04_NumericalSummaries.pdf) | - | IMS Sections 5.2, 5.4, and 5.6 |
| Wed 9/18 | [Tables](lectures/05_Tables.pdf) | [Tables Lab](labs/tables_and_descriptions_lab.html) [[solution]](labs/tables_lab_solutions.html) | - |
| Fri 9/20 | [Study Design](lectures/06_StudyDesign.pdf) | [Design Lab](labs/Design_lab.html) [[solution]](labs/design_lab_solutions.html) | IMS Chapter 2 (pgs. 28-37) |

**Assignments and Deadlines**

1) [Homework 1](homework/Homework1.html) due Monday 9/16 at 10pm.
2) [ggplot lab](labs/ggplot2_lab.html) due Monday 9/16 at 10pm.
4) [Tables Lab](labs/tables_and_descriptions_lab.html) due Friday 9/20 at 10pm.
5) [Design Lab](labs/Design_lab.html) due Monday 9/23 at 10pm.
6) [Homework 2](homework/Homework2_115.html) due Friday 9/27 at 10pm.

---

### Week 5 (Correlation and Regression)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/23 | [Correlation](lectures/07_Correlation.pdf) | [Design Lab](labs/Design_lab.html) [[solution]](labs/design_lab_solutions.html) | - |
| Wed 9/25 | [Linear Regression](lectures/08_LinearRegression.pdf) | [Regression Lab](labs/corr_regression_lab.html) [[solutions]](labs/corr_regression_lab_solutions.html) | - |
| Fri 9/27 | [Regression (Cat. Predictor)](lectures/09_LinearRegression_Categorical.pdf) | [Regression Lab](labs/corr_regression_lab.html) [[solutions]](labs/corr_regression_lab_solutions.html) | - |

**Assignments and Deadlines**

1) [Design Lab](labs/Design_lab.html) due Monday 9/23 at 10pm.
2) [Homework 2](homework/Homework2_115.html) due Friday 9/27 at 10pm.
3) [Homework 3](homework/Homework3.html) due Friday 10/04 at 10pm. (I recommend starting this early and finishing it before the exam on Wednesday as it is very good practice)

---

### Week 6 (Exam)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/30 | Review | - | - |
| Wed 10/02 | Exam | - | - |
| Fri 10/04 | dplyr | [dplyr Lab](labs/dplyr_lab.html) | - |

**Assignments and Deadlines**

1) [Regression Lab](labs/corr_regression_lab.html) due Monday 9/30 at 10pm.
2) [Homework 3](homework/Homework3.html) due Monday 10/07 at 10pm.
3) [dplyr Lab](labs/dplyr_lab.html) due Monday 10/07 at 10pm.

---

## Exam \#2 Content

### Week 7 (Probability and Sampling)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 10/07 | [Probability](lectures/10_ProbabilityRules.pdf) | [Probability Lab](labs/probabilities_lab.html) | - |
| Wed 10/09 | [Odds and Risk](lectures/11_Odds_Risk.pdf) | [Probability Lab Cont'd] | - |
| Fri 10/11 | [Sampling Distributions](lectures/12_SamplingDistributions.pdf) | - | - |

**Assignments and Deadlines**

1) [Exam 1 Corrections](homework/exam1_corrections.html) due Friday 10/11 at 10pm.
2) [Probability Lab](labs/probabilities_lab.html) due Friday 10/11 at 10pm.
3) [Homework 4](homework/Homework4_115) due Friday 10/18 at 10pm.

### Week 8 (Normal Distribution and Intervals)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 10/14 | [Normal Distribution](lectures/NormalDistribution.pdf) | [CI Lab 1](labs/normal_and_confidence_intervals.html) | - |
| Wed 10/16 | [Confidence Intervals for Pop. Mean](lectures/ConfidenceIntervals.pdf) | [CI Lab 1 cont'd] | - |
| Fri 10/18 | [More on CIs](lectures/CI_t_adjustments.pdf) | [CI Lab 2](labs/Confidence_Intervals_Lab_115.html) | [CI for Means -- Quick Guide](CI_for_means_quickguide.html) |

**Assignments and Deadlines**

1) [Homework 4](homework/Homework4_115.html) -- due Friday 10/18 at 10pm.
2) [CI Lab 1](labs/normal_and_confidence_intervals.html) due Friday 10/18 at 10pm.
3) [Homework 5](homework/Homework5_115.html) -- due Friday 11/01 after break at 10pm

---

### Week 9 (Confidence Intervals)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 10/28 | [CI for Diff. in Means](lectures/CI_diffmeans.pdf) | [CI Lab 2](labs/Confidence_Intervals_Lab_115.html) cont'd | IMS Section 19.2.1-19.2.5 (pg. 325-333), 20.4 (pg. 351-352) |
| Wed 10/30 | [CIs for Proportions](lectures/CI_proportions.pdf) | [CI Lab 2](labs/Confidence_Intervals_Lab_115.html) cont'd | IMS 16.2.1-16.2.4 (pg. 261-264), 17.3.1-17.3.2 (pg. 285-288), [[CI for Proportions - Quick Guide]](CI_for_props_quickguide.html) |
| Fri 11/01 | [Elections and Polling Stuff](lectures/PollingMethods.pdf) | - | EXTRA: [[PRC Info about elections]](https://www.pewresearch.org/short-reads/2024/08/28/key-things-to-know-about-us-election-polling-in-2024/) and [[Tied Polls]](https://www.nbcnews.com/politics/2024-election/state-poll-results-show-ties-are-tied-voters-pollsters-rcna177703?utm_source=substack&utm_medium=email) |

**Assignments and Deadlines**

1) [Homework 5](homework/Homework5_115.html) due Friday 11/01 at 10pm.
2) [CI Lab 2](labs/Confidence_Intervals_Lab_115.html) due Friday 11/01 at 10pm.
3) [Homework 6](homework/Homework6_115.html) due Friday 11/08 at 10pm.
3) Exam 2 will be on Wednesday 11/13 during normal class time.

---

### Week 10 (Bootstrap and Hypothesis Testing)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 11/04 | [Bootstrapping](lectures/Bootstrapping.pdf) | [Bootstrapping Lab](labs/Bootstrapping_Lab.html) | IMS Chapter 12 (pg. 197-207) |
| Wed 11/06 | - | - | - |
| Fri 11/07 | HW Day + Review | - | - |

**Assignments and Deadlines**

1) [Bootstrapping Lab](labs/Bootstrapping_Lab.html) due Friday 11/08 at 10pm.
2) [Homework 6](homework/Homework6_115.html) due Friday 11/08 at 10pm.

---

### Week 11 (Exam 2)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 11/11 | Review Day | [Practice Exam] | - |
| Wed 11/13 | Exam Day | - | - |
| Fri 11/15 | Project | [How to Lie with Stats Lab](labs/HowtoLiewithStatsLab.html) | [How to Lie with Stats Book](https://www.horace.org/blog/wp-content/uploads/2012/05/How-to-Lie-With-Statistics-1954-Huff.pdf) Chapter 5 -- "The Gee-Whiz Graph" (pg. 60-65) [Typed Copy](book_excerpts/HTLWS-GeeWhizGraph.pdf)|

**Assignments and Deadlines**

1) [Final Project Info](exams/SST115_project.html)
2) [How to Lie with Stats Lab](labs/HowtoLiewithStatsLab.html) due Monday 11/18 at 10pm.
3) [Homework 7 - Course Feedback](homework/Homework7_feedback.html) due Friday 11/22 at 10pm.
4) Read [HTLWS](book_excerpts/HTLWS-GeeWhizGraph.pdf) Chapter 5 -- "The Gee-Whiz Graph" (pg. 60-65) 


---

### Week 12 (Hypothesis Testing)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 11/18 | [Hypothesis Testing 1](lectures/HypothesisTesting1_115.pdf) | [Testing Worksheet (PDF)](labs/sst115_hyptesting_worksheet.pdf) [Webpage Format](labs/sst115_hyptesting_worksheet.html) | - |
| Wed 11/20 | [HT - P-values and Test-stats](lectures/HypothesisTesting2_115.pdf) | [Testing Worksheet 2 (PDF)](labs/sst115_hyptesting_worksheet2.pdf) [Webpage Format](labs/sst115_hyptesting_worksheet2.html) | - |
| Fri 11/22 | [HT - Props and Means](lectures/HypothesisTesting3_115.pdf) | [Testing Worksheet 3 (PDF)](labs/sst115_hyptesting_worksheet3.pdf) [Webpage Format](labs/sst115_hyptesting_worksheet3.html) | - |

**Assignments and Deadlines**

1) [Final Project Info](exams/SST115_project.html) groups due Wednesday 11/20 at 10pm.
2) [Testing Worksheet (PDF)](labs/sst115_hyptesting_worksheet.pdf) scanned and uploaded to Gradescope by Wednesday 11/20 at 10pm.
3) [Testing Worksheet 2 (PDF)](labs/sst115_hyptesting_worksheet2.pdf) scanned and uploaded to Gradescope by Friday 11/22 at 10pm.
4) [Homework 7 - Course Feedback](homework/Homework7_feedback.html) due Friday 11/22 at 10pm.
5) Homework 8 will be posted Friday night 11/22.
6) Exam corrections (date TBD)

---

### Exam 1 Info

Exam 1 will be in-class Wednesday Oct 2.

[[Exam 1 Topics Outline]](exams/topic_list_exam1.html)

[[Practice Exam 1]](exams/practice_exam1.pdf)

---

### Exam 2 Info

Exam 2 will be in-class Wednesday 11/13.

[[Exam 2 Topics Outline]](exams/topic_list_exam2_115.html)

[Practice Exam](exams/practice_exam2_115.html)

---

### Solutions

**Labs**

[Intro to R Solutions](labs/01_introR_solutions.html)

[Data Viz Lab Solutions](labs/DataVisualizationLab_Solutions.html)

[ggplot lab Solutions](labs/ggplot_lab_solutions.html)

[Design Lab Solutions](labs/design_lab_solutions.html)

[Regression Lab Solutions](labs/corr_regression_lab_solutions.html)

[Probabily Lab Solutions](labs/probabilities_lab_solutions.html)

[CI Lab 1 Solutions](labs/normal_and_confidence_intervals_solutions.html)

[CI Lab 2 Solutions](labs/Confidence_Intervals_Lab_2_solutions.html)

**Selected HWs**

[Homework 2 Solutions](homework/Homework2_solutions.html)

[Homework 6 Solutions](homework/Homework6_115_solutions.html)