---
title: "SST-115 Introduction to Statistics (Spring 2025)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

# Syllabus

Welcome to the course website for SST 115, Introduction to Statistics. To begin, you can find the course syllabus linked below:

- [Click here](syllabus115s25.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

# Course Materials

## Exam \#1 Content

### Week 1 (Introduction)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Wed 1/22 | [Syllabus](syllabus115s25.html) | - | - |
| Fri 1/24 | [Introduction](Lectures_Spring25/Introduction.pdf) | [Lab](Labs_Spring25/00_markdown.html) | IMS Sections 1.2.1-1.2.3 |

**Assignments and Deadlines**

1) Install R (https://cran.r-project.org/)
2) Install RStudio (https://posit.co/download/rstudio-desktop/)

---

### Week 2 (Intro to R & Data Visualization)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 1/27 | [Intro to R](Lectures_Spring25/01_R_introduction.pdf) | [Intro R Lab](Labs_Spring25/01_introR.html) | - |
| Wed 1/29 | [Data Visualization](Lectures_Spring25/02_DescribingData.pdf) | [Intro R Lab](Labs_Spring25/01_introR.html) cont'd | - |
| Fri 1/31 | No Class  | - |  - |

**Assignments and Deadlines**

1) Intro R Lab due Sunday 2/02 at 10pm. I only want to see the 3 questions from the lab in your submission file, not the entire text of the tutorial lab. Practice formatting to make everything look pretty. Make sure to select answers in your submission on Gradescope.

--- 

### Week 3 (Data Visualization and Numerical Summaries)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/03 | [Data Visualization Part 2](Lectures_Spring25/03_DataVisualization_Part2.pdf) | [Data Viz Lab](Labs_Spring25/DataVisualizationLab.html) and [Template](Labs_Spring25/DataVisualizationLab.Rmd)| - |
| Wed 2/05 | - | [ggplot lab](Labs_Spring25/ggplot2_lab.html) | - |
| Fri 2/07 | - | [ggplot lab](Labs_Spring25/ggplot2_lab.html) cont'd | - |

**Assignments and Deadlines**

1) [Data Viz Lab](Labs_Spring25/DataVisualizationLab.html) due Wednesday 2/05 at 10pm.
2) [Homework 1](Homework_Spring25/Homework1.html) is assigned Monday 2/03 and will be due the following Monday 2/10 at 10pm. The R markdown file for writing your answers can be found [here](Homework_Spring25/Homework1.Rmd)
3) [ggplot lab](Labs_Spring25/ggplot2_lab.html) due Monday 2/10 at 10pm.

---

### Week 4 (Describing Data / Study Design)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/10 | [Numerical Summaries](Lectures_Spring25/04_NumericalSummaries.pdf) | - | IMS Sections 5.2, 5.4, and 5.6 |
| Wed 2/12 | [Tables](Lectures_Spring25/05_Tables.pdf) | [Tables Lab](Labs_Spring25/tables_and_descriptions_lab.html) | - |
| Fri 2/14 | [Study Design](Lectures_Spring25/06_StudyDesign.pdf) | [Design Lab](Labs_Spring25/Design_lab.html) | IMS Chapter 2 (pgs. 28-37) |

**Assignments and Deadlines**

1) [Homework 2](Homework_Spring25/Homework2.html) assigned Wed 2/12 and due Friday 2/21 at 10pm.
2) [Tables Lab](Labs_Spring25/tables_and_descriptions_lab.html) due Wednesday 2/19 at 10pm.
3) [Design Lab](Labs_Spring25/Design_lab.html) due Wednesday 2/19 at 10pm.
4) Exam 1 will be Wednesday 2/26 during normal class time. Monday 2/24 will be a review day.

---

### Week 5 (Correlation and Regression)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/17 | Lab and Homework Day | - | - |
| Wed 2/19 | [Correlation](Lectures_Spring25/07_Correlation.pdf) | [Correlation and Regression Lab](Labs_Spring25/corr_regression_lab.html) | - |
| Fri 2/21 | [Linear Regression](Lectures_Spring25/08_LinearRegression.pdf) | [Correlation and Regression Lab](Labs_Spring25/corr_regression_lab.html) | - |

**Assignments and Deadlines**

1) [Homework 3](Homework_Spring25/Homework3.html) is due Friday 2/27 at 10pm. The HW is extremely similar to some exam questions. I recommend finishing this early.
2) Exam 1 will be Wednesday 2/26 during normal class time. Monday 2/24 will be a review day.

---

### Week 6 (Exam 1)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/24 | Review Day | - | Optional: IMS Chapter 7.1 - 7.2.4 (pages 105-119, avoid strength of fit section) |
| Wed 2/26 | Exam 1 | - | - |
| Fri 2/28 | - | [dplyr Lab](Labs_Spring25/dplyr_lab.html) | - |

**Assignments and Deadlines**

1) [Regression Lab](Labs_Spring25/corr_regression_lab.html) due Monday 2/24 at 10pm.
2) [dplyr Lab](Labs_Spring25/dplyr_lab.html) due Wednesday 3/05 at 10pm.

---

## Exam \#2 Content

### Week 7 (Probability)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 3/03 | [Probability 1](Lectures_Spring25/Probability1.pdf) | [Probability Worksheet 1](Labs_Spring25/ProbWorksheet1.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections 3.1.1-3.1.4 and 3.1.6|
| Wed 3/05 | [Probability 2](Lectures_Spring25/Probability2.pdf) | [Probability Worksheet 2](Labs_Spring25/ProbWorksheet2.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections 3.1.5 and 3.2.1-3.2.5 |
| Fri 3/07 | [Odds and Relative Risk](Lectures_Spring25/Odds_Risk.pdf) | [Probability Worksheet 3](Labs_Spring25/ProbWorksheet3.pdf) | - |

**Assignments and Deadlines**

1) [Homework 4](Homework_Spring25/Homework4.html) due Friday 3/28 at 10pm.
2) [Exam Corrections](Homework_Spring25/exam1_corrections.pdf) due Friday 3/28 at 10pm (exam score is capped at 80\% for corrections).

---

### Week 8\* (Normal Distributions)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 3/24 | [Normal Distributions](Lectures_Spring25/NormalDistribution.pdf) | [Normal Distribution Lab](Labs_Spring25/normaldist_probabilities_lab_115.html) | - |
| Wed 3/26 | [Standard Deviation and Variance](Lectures_Spring25/Standard_Deviation_and_Variance.pdf) | [Normal Distribution Lab](Labs_Spring25/normaldist_probabilities_lab_115.html) cont'd | - |
| Fri 3/28 | [Sampling Distributions](Lectures_Spring25/SamplingDistributions.pdf) | [Sampling Distribution Lab](Labs_Spring25/SamplingDist_Lab.html) | - |

**Assignments and Deadlines**

1) Probability Worksheets scanned and uploaded to gradescope by Wednesday 3/26 at 10pm.
2) Normal Distribution Lab due Friday 3/28 at 10pm.
3) Sampling Distributions Lab due Sunday 3/30 at 10pm.

---


## Exam 1 Info

Exam 1 will be in-class Wednesday Feb. 26.

[Exam 1 Topics Outline](Exams_Spring25/topic_list_exam1.html)

[Practice Exam 1](Exams_Spring25/practice_exam1.html) file and ([PDF Format](Exams_Spring25/practice_exam1.pdf))

---

### Lab Solutions

[Intro R Lab](Labs_Spring25/01_introR_solutions.html)

[Data Viz Lab](Labs_Spring25/DataVisualizationLab_Solutions.html)

[Ggplot2 Lab](Labs_Spring25/ggplot_lab_solutions.html)

[Tables Lab](Labs_Spring25/tables_lab_solutions.html)

[Design Lab](Labs_Spring25/design_lab_solutions.html)

[Regression Lab](Labs_Spring25/corr_regression_lab_solutions.html)

### Selected HW Solutions

[Homework 2](Homework_Spring25/Homework2_solutions.pdf)