---
title: "STA-209 - Applied Statistics (Spring 2025)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

# Syllabus

Welcome to the course website for STAT 209, Introduction to Applied Statistics. To begin, you can find the course syllabus linked below:

- [Click here](syllabus209s25.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

# Course Materials

## Exam \#1 Content

### Week 1 (Intro)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Wed 1/22 | [Syllabus](syllabus209s25.html) | - | - |
| Fri 1/24 | [Introduction](Lectures_Spring25/Introduction.pdf) | [Lab](Labs_Spring25/00_markdown.html) | IMS Sections 1.2.1-1.2.3 |

**Assignments and Deadlines**

1) Install R (https://cran.r-project.org/)
2) Install RStudio (https://posit.co/download/rstudio-desktop/)

---

### Week 2 (Intro to R & Data Visualization)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 1/27 | [Intro to R](Lectures_Spring25/01_R_introduction.pdf) | [Intro R Lab](Labs_Spring25/01_introR.html) | - |
| Wed 1/22 | [Data Visualization](Lectures_Spring25/02_DescribingData.pdf) | [Intro R Lab](Labs_Spring25/01_introR.html) cont'd | - |
| Fri 1/24 | No Class  | - |  - |

**Assignments and Deadlines**

1) Intro R Lab due Sunday 2/02 at 10pm. I only want to see the 3 questions from the lab in your submission file, not the entire text of the tutorial lab. Practice formatting to make everything look pretty. Make sure to select answers in your submission on Gradescope.

--- 

### Week 3 (Data Visualization and Numerical Summaries)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/03 | [Data Visualization Part 2](Lectures_Spring25/03_DataVisualization_Part2.pdf) | [Data Viz Lab](Labs_Spring25/DataVisualizationLab.html) and [Template](Labs_Spring25/DataVisualizationLab.Rmd)| - |
| Wed 2/05 | - | [ggplot lab](Labs_Spring25/ggplot2_lab.html) | - |
| Fri 2/07 | - | [ggplot lab](Labs_Spring25/ggplot2_lab.html) cont'd | - |

**Assignments and Deadlines**

1) [Data Viz Lab](Labs_Spring25/DataVisualizationLab.html) due Wednesday 2/05 at 10pm.
2) [Homework 1](Homework_Spring25/Homework1.html) is assigned Monday 2/03 and will be due the following Monday 2/10 at 10pm. The R markdown file for writing your answers can be found [here](Homework_Spring25/Homework1.Rmd)
3) [ggplot lab](Labs_Spring25/ggplot2_lab.html) due Monday 2/10 at 10pm.

---

### Week 4 (Describing Data / Study Design)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/10 | [Numerical Summaries](Lectures_Spring25/04_NumericalSummaries.pdf) | - | IMS Sections 5.2, 5.4, and 5.6 |
| Wed 2/12 | [Tables](Lectures_Spring25/05_Tables.pdf) | [Tables Lab](Labs_Spring25/tables_and_descriptions_lab.html) | - |
| Fri 2/14 | [Study Design](Lectures_Spring25/06_StudyDesign.pdf) | [Design Lab](Labs_Spring25/Design_lab.html) | IMS Chapter 2 (pgs. 28-37) |

**Assignments and Deadlines**

1) [Homework 2](Homework_Spring25/Homework2.html) assigned Wed 2/12 and due Friday 2/21 at 10pm.

### Lab Solutions

[Intro R Lab](Labs_Spring25/01_introR_solutions.html)

[Data Viz Lab](Labs_Spring25/DataVisualizationLab_Solutions.html)