---
title: "STA-209 - Applied Statistics (Spring 2026)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

<hr style="border: none; border-top: 5px solid black;">

# Syllabus

Welcome to the course website for STAT 209, Introduction to Applied Statistics. To begin, you can find the course syllabus linked below:

- [Click here](syllabus209s26.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

<hr style="border: none; border-top: 5px solid black;">

## Exam \#1 Content

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Wed 1/21 | [Syllabus](syllabus209s26.html) and [Introduction](Lectures/01_Introduction.pdf) | [Lab](Labs/R_packages.html) | IMS Sections 1.2.1-1.2.3 before Monday |
| Fri 1/23 | [Intro to R](Lectures/R_Introduction.pdf) | [Intro R Lab](Labs/R_Introduction.html) | - |

**Assignments and Deadlines**

1) Install R (https://cran.r-project.org/) before Friday.
2) Install RStudio (https://posit.co/download/rstudio-desktop/) before Friday.

---

## Week 2 (Quantiative Variables)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 1/26 | - | [Intro R Lab](Labs/R_Introduction.html) cont'd | - |
| Wed 1/28 | [Quantitative Variables -- Part 1](Lectures/QuantVar1.pdf) | [Quant Var Lab](Labs/QuantVarLab.html) | IMS Chapters 5.2-5.5 (pg. 74-82) |
| Fri 1/30 | [Quantitative Variables -- Part 2](Lectures/QuantVar2.pdf) | [Quant Var Lab](Labs/QuantVarLab.html) | - |

---

## Week 3 (Categorical Variables)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/02 | [Categorical Variables](Lectures/CategoricalVariables.pdf) | [Cat Var Lab](Labs/CatVarLab.html) [[Template]](Labs/CatVarLab.Rmd) | - |
| Wed 2/04 | [Tables (for Categorical Information)](Lectures/Tables.pdf) | [Tables Lab](Labs/TablesLab.html) | - |
| Fri 2/05 | [GGplot2] | [ggplot2 Lab](Labs/ggplot2_lab.html) | - |

---

## Week 4

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/09 | - | [ggplot2 Lab](Labs/ggplot2_lab.html) cont'd | - |
| Wed 2/11 | [Probability 1 -- Basics](Lectures/Probability1.pdf) | [Probability Worksheet 1](Labs/ProbWorksheet1.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections (see below) |
| Fri 2/13 | [Probability 2 -- Independence](Lectures/Probability2.pdf) | [Probability Worksheet 2](Labs/ProbWorksheet2.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections (see below) |

---

## Week 5

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/16 | [Probability 3 -- Odds/Risk](Lectures/Probability3.pdf) | [Probability Worksheet 3](Labs/ProbWorksheet3.pdf) | - |
| Wed 2/18 | [Study Design -- Sampling Methods](Lectures/StudyDesign1.pdf) | [Study Design Lab](Labs/StudyDesignLab.html) | - |
| Fri 2/20 | No Class | - | - |

---

## Week 6

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 2/23 | Homework and Lab Workday | - | - |
| Wed 2/25 | [Study Design 2](Lectures/StudyDesign2.pdf) | [Study Design 2 Lab](Labs/StudyDesign2_Lab.html) | - |
| Fri 2/27 | Exam 1 | - | - |

# Week 7 (Statistical Framework)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 3/02 | [Random Variables](Lectures/RandomVariables.pdf) | - | - |
| Wed 3/04 | [Normal Distributions](Lectures/NormalDistribution.pdf) | [Normal Probability R Guide](Labs/NormalDistribution_Lab_Setup.html) and [Normal Prob Practice](Labs/NormalDistribution_Lab.pdf) | - |
| Fri 3/06 | [Sampling Distributions](Lectures/SamplingDistributions.pdf) | [Sampling Distribution Lab](Labs/SamplingDistribution_Lab.html) | - |

## Week 10* (Confidence Intervals)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 3/23 | [Confidence Intervals Pt. 1 (Means)](Lectures/CI1.pdf) | - | - |
| Wed 3/25 | - | - | - |
| Fri 3/27 | CI Review | [CI Lab 1](Labs/CI_Lab1.html) | - |



## Week 11 (Confidence Intervals Cont'd)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 3/30 | [Confidence Intervals Pt. 2 (t-Distribution)](Lectures/CI2.pdf) | [CI Lab 1](Labs/CI_Lab1.html) cont'd | - |
| Wed 4/01 | [Project Day](Labs/Project1.html) | - | - |
| Fri 4/03 | [Confidence Intervals Pt. 3 (Diff in Means)](Lectures/CI3.pdf) | [CI Lab 2](Labs/CI_Lab2.html) | IMS 19.2.1-19.2.4 (pg. 325-332) |

## Week 12 (Confidence Intervals)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 4/06 | [Confidence Intervals Pt. 4 (Proportions)](Lectures/CI4.pdf) | [CI Lab 3](Labs/CI_Lab3.html) | - |
| Wed 4/08 | [More on CI Conditions](Lectures/CI5.pdf) | - | - |
| Fri 4/10 | [Hypothesis Testing Intro](Lectures/HT1.pdf) | - | IMS Chapter 11.3 (pg. 188 - 189, DO NOT READ pg.190) |

## Week 13 (Hypothesis Testing + Exam)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 4/13 | [HT Part 2](Lectures/HT2.pdf) | [Testing Lab 1](Labs/TestingLab1.html) | - |
| Wed 4/15 | [HT Part 3 -- Test Statistics](Lectures/HT3.pdf) | [Testing Lab 2](Labs/TestingLab2.html) | - |
| Fri 4/17 | In-class Exam | - | - |

## Week 14 (Hypothesis Testing + Dplyr)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 4/20 | - | [Dplyr](Labs/dplyr_lab.html) | - |
| Wed 4/23 | [HT Part 4 -- Other Scenarios](Lectures/HT4.pdf) | [Testing Lab 3 (Worksheet)](Labs/TestingLab3_Worksheet.pdf) | - |
| Fri 4/25 | [HT Part 5](Lectures/HT5.pdf) | [Testing Lab 4 (Worksheet)](Labs/TestingLab4_Worksheet.pdf) | - |

---

## Week 15 (Scatterplots, Correlation, Regression)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 4/27 | [Scatterplots and Correlation](Lectures/Correlation.pdf) | [Corr and Tests Lab](Labs/Corr_and_Tests_Lab.html) | - |
| Wed 4/29 | ['Simple' Linear Regression](Lectures/SLR.pdf) | [Regression Lab 1](Labs/Regression1.html) | - |
| Fri 5/01 | [SLR2 -- Categorical Predictors](Lectures/SLR2_Cat.pdf) | [Regression Lab 2](Labs/Regression2.html) | - |

## Week 16 (Multiple Regression + ANOVA)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 5/04 | [Multiple Regression](Lectures/MLR.pdf) | [MLR Lab](Labs/MLR_Lab.html) | [IMS Chapter 8.1-8.3 (pg. 136-143)] |
| Wed 5/06 | [Regression Errors](Lectures/Regression_Error.pdf) | [MLR Lab](Labs/MLR_Lab.html) cont'd | [To Explain or To Predict](Reading_ExplainPredict.html) |
| Fri 5/08 | [ANOVA](Lectures/Anova1.pdf) | [MLR Worksheet](Labs/mlr_funsheet.pdf) | - |

**Final Exam Info:** Final exam will be on Wednesday 5/13 at 9am in the normal class room. The exam will not be 3 hours in length. Review material will be posted later this week.


### Reading Assignments

* IMS Sections 1.2.1-1.2.3 before Monday 1/26.
* IMS Chapters 5.2-5.5 (pg. 74-82) before Monday 2/02
* [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Chapter 3.1 before Friday 2/13
* IMS Chapters 19.2.1-19.2.4 (pg. 325-332)

### Lab Assignments

[Intro R Lab](Labs/R_Introduction.html) due on Gradescope Wednesday 1/28 at 10pm. Gradescope info will be given in Class on Monday.

[Quant Var Lab](Labs/QuantVarLab.html) due Wednesday 2/04 at 10pm. [(**Solution**)](Labs/QuantVarLab_Solutions.html)

[Cat Var Lab](Labs/CatVarLab.html) due Friday 2/06 at 10pm. [(**Solution**)](Labs/CatVarLab_Solutions.html)

[Tables Lab](Labs/TablesLab.html) due Sunday 2/08 at 10pm. [(**Solution**)](Labs/TablesLab_Solutions.html)

[ggplot2 Lab](Labs/ggplot2_lab.html) due Wednesday 2/11 at 10pm. 

Probability Worksheets checked for credit at start of class on Wednesday 2/18. [(**Solution**)](Labs/ProbWorksheets_Solutions.pdf)

[Normal Prob Practice](Labs/NormalDistribution_Lab.pdf) uploaded to Gradescope by Thursday 3/05 at 10pm. [(**Solution**)](Labs/NormalDistribution_Lab_Solutions.html)

[Sampling Distribution Lab](Labs/SamplingDistribution_Lab.html) due Sunday 3/08 at 10pm. [(**Solution**)](Labs/SamplingDistribution_Lab_Solutions.html)

[CI Lab 1](Labs/CI_Lab1.html) will have more added to it on Monday 3/30 and be due Wed 4/01 at 10pm. [(**Solution**)](Labs/CI_Lab1_Sol.html)

[CI Lab 2](Labs/CI_Lab2.html) due Sunday 4/05 at 10pm. [(**Solution**)](Labs/CI_Lab2_Sol.html)

[CI Lab 3](Labs/CI_Lab3.html) due Thursday 4/09 at 10pm. [(**Solution**)](Labs/CI_Lab3_Sol.html)

[Testing Lab 1](Labs/TestingLab1.html) due Sunday 4/19 at 10pm.

[Testing Lab 2](Labs/TestingLab2.html) due Monday 4/20 at 10pm.

[Dplyr Lab](Labs/dplyr.html) due Wednesday 4/22 at 10pm.

[Testing Lab 3 (Worksheet)](Labs/TestingLab3_Worksheet.pdf) due Friday 4/24 at 10pm.

[Testing Lab 4 (Worksheet) Solutions](Labs/TestingLab4_Worksheet.pdf)

[Corr and Tests Lab Solutions](Labs/Corr_and_Tests_Lab_Sol.html)

[Regression Lab 1](Labs/Regression1.html) and Wednesday 5/06 at 10pm. (adjusted gradescope submission date) [Solutions](regression1_sol.html)

[Regression Lab 2](Labs/Regression2.html) due Wednesday 5/06 at 10pm. (adjusted gradescope submission date)


### Homework Assignments

[Homework 1](Homework/Homework1.html) due Friday 2/20 at 10pm.

[Homework 2](Homework/Homework2.html) due Friday 2/27 at 10pm.

[Homework 3](Homework/Homework3.html) due Friday 3/06 at 10pm.** See class announcement email about starting this early.

[Exam 1 Correction](Exams/exam1_corrections.html) due Friday 3/27 at 10pm. Gradescope submission will be posted.

[Homework 4](Homework/Homework4.html) due Wednesday 4/15 at 10pm. Primarily focused on confidence intervals.

[Homework 5](Homework/Homework5.html) due Sunday 4/19 at 10pm. Primarily focused on confidence intervals. *I recommend completing this before the exam -- extremely beneficial.*

[Homework 6](Homework/HW6.html) due Wednesday 5/06 at 10pm.

[Homework 7](Homework/Homework7.html) due Sunday  5/10 at 10pm.

---

### Exam Info

**Exam 1** will be on Feb 2/27 during normal class time within the classroom. **Note:** There may be a few questions asking about random assignment or experiment vocabulary terms in the practice documents -- these topics will not be on the exam due to the missed class on 2/20.

[[Practice Exam 1]](Exams/practice_exam1.pdf)

[[Exam 1 Topics List]](Exams/topic_list_exam1.html)

**Exam 2** will be on Friday 4/17 during normal class time within the regular classroom.

[[Exam 2 Topics List]](Exams/topic_list_exam2.html)

[[Exam 2 Short Answer]](Exams/exam2_shortanswer.html)

[[Exam 2 CI Formulas]](Exams/exam2_formulas.html)

#### Exam 3

[Exam 3 Short Answer Practice](Exams/exam3_shortanswer.html)

[Exam 3 Topics List](Exams/Exam3Topics.pdf)

[Exam 3 Practice 1](Exams/exam3_practice1.pdf) [A snippet from a previous review related to regression concepts]

[Exam 3 Practice 2](Exams/exam3_practice2.pdf) [A snippet from a previous review related to regression concepts]

[Exam 3 Formula Sheet] TBP

**Note:** No solutions will be posted for Testing Worksheet 4 or HW6 or HW7. You may meet with me during office hours to discuss these assignments. MLR Lab solutions and MLR worksheet solutions will be posted Saturday night.

<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 2/02 | - | - | - | -->
<!-- | Wed 2/04 | - | - | - | -->
<!-- | Fri 2/05 | - | - | - | -->