---
title: "STA-209 - Applied Statistics (Fall 2025)"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
  pdf_document:
    toc: true
---

$~$

Last updated: `r format(Sys.time(), "%a %b %e %Y, %H:%M")`

<hr style="border: none; border-top: 5px solid black;">

# Syllabus

Welcome to the course website for STAT 209, Introduction to Applied Statistics. To begin, you can find the course syllabus linked below:

- [Click here](syllabus209f25.html) to view the course syllabus

You can locate course content by scrolling, or by using the navigation bar in the upper left.  

Please note: material will not be posted until we've reached that point in the course.

<hr style="border: none; border-top: 5px solid black;">

## Exam \#1 Content

### Week 1 (Intro)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Fri 8/29 | [Syllabus](syllabus209f25.html) and [Introduction](Lectures/209_Introduction.pdf) (update pending) | [Lab](Labs/00_markdown.html) | IMS Sections 1.2.1-1.2.3 |

**Assignments and Deadlines**

1) Install R (https://cran.r-project.org/)
2) Install RStudio (https://posit.co/download/rstudio-desktop/)

---

### Week 2 (Intro to R & Data Visualization)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/01 | Labor Day (no class) | - | - |
| Wed 9/03 | [Intro to R](Lectures/01_R_introduction.pdf) | [Intro R Lab](Labs/01_introR.html) | - |
| Fri 9/05 | - | [Intro R Lab](Labs/01_introR.html) cont'd | IMS 5.2-5.5 (pgs. 74-82) |

**Assignments and Deadlines**

1) [Intro R Lab](Labs/01_introR.html) due Sunday at 10pm via Gradescope (assign all pages to Question 1). Gradescope assingment will be posted on Friday.
2) Read IMS 5.2-5.5 (pgs. 74-82) before Monday's class.

---

### Week 3 (Data Visualization and Summaries)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/08 | [Quantitative Variables -- 1](Lectures/QuantVar1.pdf) | [Quant Var Lab](Labs/QuantVarLab.html) and [Template](Labs/QuantVarLab.Rmd) | - |
| Wed 9/10 | [Quantitative Variables -- 2](Lectures/QuantVar2.pdf) | [Quant Var Lab](Labs/QuantVarLab.html) cont'd | - |
| Fri 9/12 | [Categorical Variables](Lectures/CategoricalVariables.pdf) | [Cat Var Lab](Labs/CatVarLab.html) [(Template)](Labs/CatVarLab.Rmd) | - |

**Assignments and Deadlines**

1) [Quant Var Lab](Labs/QuantVarLab.html) due Friday 9/12 at 10pm. Make sure to assign pages to the question.
2) [Homework 1](Homework/Homework1.html) [(Template)](Homework/Homework1.Rmd) due Friday 9/19 at 10pm.
3) [Cat Var Lab](Labs/CatVarLab.html) due Monday 9/15 at 10pm.

---

### Week 4 (Tables and ggplot2)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/15 | [Tables](Lectures/Tables.pdf) | [Tables Lab](Labs/TablesLab.html)| - |
| Wed 9/17 | [ggplot2 Overview] | [ggplot2 lab](Labs/ggplot2_lab.html) | - |
| Fri 9/19 | [Graphics Accessibility] | [ggplot2 lab](Labs/ggplot2_lab.html) cont'd | - |

**Assignments and Deadlines**

1) Tables lab due Wednesday 9/17 at 10pm.
2) [ggplot2 lab](Labs/ggplot2_lab.html) due Monday 9/22 at 10pm.
3) [Homework 2](Homework/Homework2.html) due Friday 9/26 at 10pm.

---

### Week 5 (Probability)
| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/22 | [Study Design](Lectures/StudyDesign.pdf) | [Study Design Lab](Labs/StudyDesign_Lab.html) | -|
| Wed 9/24 | [Probability 1 -- Basics](Lectures/Probability1.pdf) | [Probability Worksheet 1](Labs/ProbWorksheet1.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections TBA|
| Fri 9/26 | [Probability 2 -- Independence](Lectures/Probability2.pdf) | [Probability Worksheet 2](Labs/ProbWorksheet2.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections TBA |

**Deadlines and Due Dates:**

1) [Study Design Lab](Labs/StudyDesign_Lab.html) due Wednesday 9/24 at 10pm.
2) [Homework 3](Homework/Homework3.html) due Friday 10/03 at 10pm. This is due after the Exam, but *please* finish it beforehand. It will be extremely good practice.

### Week 6 (Probability + Exam 1)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 9/29 | [Probability 3 -- Odds + Risk](Lectures/Probability3.pdf) | [Probability Worksheet 3](Labs/ProbWorksheet3.pdf) | - |
| Wed 10/01 | [Random Variables](Lectures/RandomVariables.pdf) | Review Time | - |
| Fri 10/03 | Exam 1 | - | - |

---

## Exam \#2 Content

### Week 7 (Normal and Sampling Distributions)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 10/06 | [Normal Distributions](Lectures/NormalDistribution.pdf) | [Normal Probability R Guide](Labs/NormalDistribution_Lab_Setup.html) and [Normal Prob Practice](Labs/NormalDistribution_Lab.pdf) | - |
| Wed 10/08 | [Sampling Distributions](Lectures/SamplingDistributions.pdf) | [Sampling Distribution Lab](Labs/SamplingDistribution_Lab.html) | - |
| Fri 10/10 | [Confidence Interval 1 (Mean)](Lectures/CI1.pdf) | [Confidence Interval Lab 1](Labs/CI_Lab1.html) | - |

**Assignments and Due Dates**:

1) [Normal Distribution Lab](Labs/NormalDistribution_Lab.pdf) due Wednesday 10/08 at 10pm.
2) [Sampling Distribution Lab](Labs/SamplingDistribution_Lab.html) due Friday 10/10 at 10pm.

### Week 8 (Confidence Intervals)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 10/13 | [Confidence Interval 2 -- t-Distribution](Lectures/CI2.pdf) | [Confidence Interval Lab 1](Labs/CI_Lab1.html) cont'd | - |
| Wed 10/15 | [Confidence Interval 3 -- Difference in Means](Lectures/CI3.pdf) | [Confidence Interval Lab 1](Labs/CI_Lab1.html) cont'd | - |
| Fri 10/17 | [Confidence Interval 4 -- Proportions](Lectures/CI4.pdf) | [Confidence Interval Lab 2](Labs/CI_Lab2.html) | - |

**Assignments and Due Dates**:

1) [Confidence Intervl Lab 1](Labs/CI_Lab1.html) due Friday 10/17 at 10pm.
2) [Homework 4](Homework/Homework4.html) due Friday 10/31 at 10pm. More will be added to this over the course of Week 8. Start early!
3) [Exam 1 Correction](Exams/exam1_corrections.html) due Monday 10/27 at 10pm. Gradescope submission will be posted.
4) [Confidence Interval Lab 2](Labs/CI_Lab2.html) due Monday 10/27 at 10pm.

---

### Week 9 (dplyr + Bootstrapping + Hypotheses)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 10/27 | - | [dplyr Lab](Labs/dplyr_lab.html) | - |
| Wed 10/29 | [Bootstrapping](Lectures/Bootstrapping.pdf) | [Bootstrapping Lab](Labs/Bootstrapping_Lab.html) | - |
| Fri 10/31 | [Hypothesis Testing Intro](Lectures/HT1.pdf) | Free Work Period | - |

**Assignments and Due Dates**

1) [dplyr Lab](Labs/dplyr_lab.html) due Wednesday 10/29 at 10pm.
2) [Bootstrapping Lab](Labs/Bootstrapping_Lab.html) due Sunday 11/02 at 10pm.
3) [Homework 5](Homework/Homework5.html) due Friday 11/07 at 10pm.
4) [Feedback Assignment](Homework/209_feedback_assign.html) due Friday 11/07 at 10pm. See details for grading. Completion $\rightarrow$ extra token.
5) Exam 2 will be on Friday Nov. 14 during scheduled class time.

---

### Week 10 (Hypothesis Testing)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 11/03 | [Hypothesis Testing 2](Lectures/HT2.pdf) | [HT Lab 1](Labs/TestingLab1.html) | - |
| Wed 11/05 | [Hypothesis Testing 3](Lectures/HT3.pdf) | [HT Lab 2](Labs/TestingLab2.html) | - |
| Fri 11/07 | [HT 4 -- More Types](Lectures/HT4.pdf) | [HT Lab 3 (Worksheet)](Labs/TestingLab3_Worksheet.pdf) | - |

---

**Deadlines and Due Dates**:

1) [Homework 5](Homework/Homework5.html) due Friday 11/07 at 10pm.
2) [Feedback Assignment](Homework/209_feedback_assign.html) due Friday 11/07 at 10pm. See details for grading. Completion $\rightarrow$ extra token.
3) [HT Lab 1](Labs/TestingLab1.html) due Friday 11/07 at 10pm.
4) [HT Lab 2](Labs/TestingLab2.html) due Sunday 11/09 at 10pm.
4) See Final Project info posted below.
5) Exam 2 on Friday 11/14 in class.
6) [HT Lab 3 (Worksheet)](Labs/TestingLab3_Worksheet.pdf) will function as HW6 due Friday 11/14 at 10pm. I suggest completing this before the exam. We will cover Q3 and Q4 in class Monday 11/10 as time permits.

---

### Week 11 (Hypothesis Testing + Exam)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 11/10 | [Hypothesis Testing 5](Lectures/HT5.pdf) | [HT Lab 4 (Worksheet)](Labs/TestingLab4_Worksheet.pdf) | [ASA P-value Statment](https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf) |
| Wed 11/12 | Review | - | - |
| Fri 11/14 | Exam | - | - |

**Assignments and Due Dates**

1) Continue to monitor project due dates.
2) [HT Lab 3 (Worksheet)](Labs/TestingLab3_Worksheet.pdf) will function as HW6 due Friday 11/14 at 10pm. I suggest completing this before the exam. We will cover Q3 and Q4 in class Monday 11/10 as time permits.
3) [HT Lab 4 (Worksheet)](Labs/TestingLab4_Worksheet.pdf) due Friday 11/10 at 10pm. DO BEFORE EXAM.
4) In-class reading quiz over ASA P-value Statement document on Monday 11/17.
5) Exam 2 on Friday 11/14. Review materials will be posted Tuesday morning.

---


## Exam \#3 Content

### Week 12 (Correlation and Regression)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 11/17 | [More on Standard Deviations](Lectures/StdDevVariance.pdf) | [SD Lab](Labs/SD_revisit.html) | - |
| Wed 11/19 | [Correlation](Lectures/Correlation.pdf) | [Correlation and Regression Lab](Labs/corr_regression_lab.html) | - |
| Fri 11/21 | [Simple Linear Regression](Lectures/SLR.pdf) | [Correlation and Regression Lab](Labs/corr_regression_lab.html) cont'd | - |

**Assignments and Due Dates**

1) [SD Lab](Labs/SD_revisit.html) due Wednesday 11/19 at 10pm.
2) [Correlation and Regression Lab](Labs/corr_regression_lab.html) due Sunday 11/23 at 10pm. More will be added to this for Friday's class.
3) Exam 3 Heads up: 2-5pm Tuesday 12/16. Dictated by the college based on in-class meet time.
4) Project dates revised.

---

### Week 13 (More on Regression)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 11/24 | [Regression -- Categorical Predictors](Lectures/SLR2_Cat.pdf) | [Regression Lab 2](Labs/Regression_Lab2.html) | - |
| Wed 11/19 | [Multiple Linear Regression 1](Lectures/MLR1.pdf) | [MLR Lab](Labs/MLR_Lab.html) |
| Fri 11/21 | No class | - | - |

**Assignments and Due Dates**

1) Start collecting and analyzing data for the exploratory analysis.
2) [Regression Lab 2](Labs/Regression_Lab2.html) due Monday 12/01 at 10pm.
3) A regression homework and reading assignment will be posted early next week.
4) MLR Lab due date TBD.
5) [Homework 7](Homework/Homework7.html) due Friday 12/12 at 10pm.

---

### Week 14 (ANOVA)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 12/01 | No Class (Weather) | - | - |
| Wed 12/03 | [ANOVA 1](Lectures/Anova1.pdf) | [ANOVA Lab](Labs/ANOVA_lab.html) | - |
| Fri 12/05 | [ANOVA 2](Lectures/Anova2.pdf) | [ANOVA Lab](Labs/ANOVA_lab.html) cont'd | [To Explain or To Predict](Homework/ReadingAssign2.html) |

**Assignments and Due Dates**

1) [MLR Lab](Labs/MLR_Lab.html) due Friday 12/05 at 10pm.
2) Exploratory Analysis for project due Friday 12/05 at 10pm.
3) [ANOVA Lab](Labs/ANOVA_lab.html) due Monday 12/08 at 10pm.
4) Exam 2 Corrections due Wednesday 12/10 at 10pm. A gradescope submission will be posted.
5) [Homework 7](Homework/Homework7.html) posted. Due Friday 12/12 at 10pm. Start Early!
6) Reading assignment 2 posted. In-class quiz will be administered at the start of class on Friday 12/12.

---

### Week 15 (ANOVA + Regression)

| Date | Lecture | Lab | Reading |
|:-----|:-------|:-----|:-----|
| Mon 12/08 | [ANOVA & Regression](Lectures/ANOVA_SLR.pdf) | Review/Work Time | - |
| Wed 12/10 | [Regression Residuals](Lectures/Regression_Error.pdf) | [Residuals Lab](Labs/RegressionError_lab.html) | - |
| Fri 12/12 | [TBD] | - | Reading Quiz |

**Assignments and Due Dates**

1) Exam 2 Corrections due Wednesday 12/10 at 10pm. A gradescope submission will be posted.
2) [Homework 7](Homework/Homework7.html) posted. Due Friday 12/12 at 10pm. Start Early!
3) Reading assignment 2 posted. In-class quiz will be administered at the start of class on Friday 12/12.


### Project Information

See [project link here](Exams/STA209_project.html) for all of the information. At my disgression I may adjust due dates back a bit to allow for more time.

1) Group assignments due Monday 11/10 at 10pm via email. 
2) Project Proposal due Sunday 11/16 at 10pm. 
3) Exploratory analysis due Friday 12/05 at 10pm (revised from 11/28)
4) Final project write-up due Friday 12/19 at 5pm (revised from 12/14)

### Lab Solutions

[(Quantitative Variabls Lab Sol)](Labs/QuantVarLab_Solutions.html)

[(Categorical Variabls Lab Sol)](Labs/CatVarLab_Solutions.html)

[(Tables Lab Solutions)](Labs/TablesLab_Solutions.html)

[(Probability Worksheet Solutions)](Labs/ProbWorksheets_Solutions.pdf)

[(Normal Distribution Practice Solutions)](Labs/NormalDistribution_Lab_Solutions.html)

[(Sampling Distributions Solutions)](Labs/SamplingDistribution_Lab_Solutions.html)

[(CI Lab 1 Solutions)](Labs/CI_Lab1_Sol.html)

[(CI Lab 2 Solutions)](Labs/CI_Lab2_Sol.html)

[HT Lab 1](Labs/TestingLab1_Sol.html)

[HT Lab 2](Labs/TestingLab2_Sol.html)

[Testing Worksheet 3](Labs/TestingLab3_Worksheet_Sol.html)

[Correlation and Regression Lab](Labs/corr_regression_lab_solutions.html)

[Regression Lab 2](Labs/Regression_Lab2_Sol.html)

[MLR Lab](Labs/MLR_Lab_Sol.html)

[ANOVA Lab](Labs/ANOVA_lab_sol.html)

---

### Selected HW Solutions

[[Homework 1 Sol]](Homework/Homework1_Solutions.html)

[[Homework 2 Sol]](Homework/Homework2_Solutions.html)

[[Homework 4 Sol]](Homework/Homework4_Solutions.html)

[[Homework 5 Sol]](Homework/Homework5_Solutions.html)

### Exam 1 Materials

[[Practice Exam 1]](Exams/practice_exam1.pdf)

[[Exam 1 Topics List]](Exams/topic_list_exam1.html)

### Exam 2 Materials

The best thing you can do to prepare for the exam is to go through the confidence interval and hypothesis test labs + homeworks. Extra material will be posted here early in Week 11.

[Exam 2 Topics Outline](Exams/topic_list_exam2.html)

[Exam 2 Short Answer Practice](Exams/exam2_shortanswer.html)

[Exam 2 Practice](Exams/practice_exam2.html)

[Exam 2 Practice Extra](Exams/practice_exam2_extra.pdf)

[Exam 2 Formula Sheet](Exams/exam2_formulas.pdf) All of this will appear as a page at the end of the exam. I may have to format it slightly differently to fit.

### Exam 3 Materials

The best prep you will have for this exam is going through the regression and ANOVA labs + HW7 and spending time to fully understand all parts. Most of the questions will be structured in ways similar to the labs. HW7 solutions will be posted on Saturday morning (after it is due). 

Below is some extra material you may find helpful. There are not extensive formulas for this exam, only those related to ANOVA will be needed. Linear regression concepts will be tested, but formulas for slopes/intercepts are unnecessary.

[Exam 3 Topics List](Exams/Exam_3_Topics_List.pdf)

[Exam 3 Short Answer Practice] (TBP)

[Exam 3 Practice A](Exams/exam3_practice1.pdf) [A snippet from a previous review related to regression concepts]

[Exam 3 Practice B](Exams/exam3_practice2.pdf) [A snippet from a previous review related to regression concepts]

[Exam 3 ANOVA Formulas](Exams/exam3_ANOVA_formulas.pdf)


<!-- **Assignments and Deadlines** -->

<!-- 1) Intro R Lab due Sunday 2/02 at 10pm. I only want to see the 3 questions from the lab in your submission file, not the entire text of the tutorial lab. Practice formatting to make everything look pretty. Make sure to select answers in your submission on Gradescope. -->

<!-- ---  -->

<!-- ### Week 3 (Data Visualization and Numerical Summaries) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 2/03 | [Data Visualization Part 2](Lectures_Spring25/03_DataVisualization_Part2.pdf) | [Data Viz Lab](Labs_Spring25/DataVisualizationLab.html) and [Template](Labs_Spring25/DataVisualizationLab.Rmd)| - | -->
<!-- | Wed 2/05 | - | [ggplot lab](Labs_Spring25/ggplot2_lab.html) | - | -->
<!-- | Fri 2/07 | - | [ggplot lab](Labs_Spring25/ggplot2_lab.html) cont'd | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) [Data Viz Lab](Labs_Spring25/DataVisualizationLab.html) due Wednesday 2/05 at 10pm. -->
<!-- 2) [Homework 1](Homework_Spring25/Homework1.html) is assigned Monday 2/03 and will be due the following Monday 2/10 at 10pm. The R markdown file for writing your answers can be found [here](Homework_Spring25/Homework1.Rmd) -->
<!-- 3) [ggplot lab](Labs_Spring25/ggplot2_lab.html) due Monday 2/10 at 10pm. -->

<!-- --- -->

<!-- ### Week 4 (Describing Data / Study Design) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 2/10 | [Numerical Summaries](Lectures_Spring25/04_NumericalSummaries.pdf) | - | IMS Sections 5.2, 5.4, and 5.6 | -->
<!-- | Wed 2/12 | [Tables](Lectures_Spring25/05_Tables.pdf) | [Tables Lab](Labs_Spring25/tables_and_descriptions_lab.html) | - | -->
<!-- | Fri 2/14 | [Study Design](Lectures_Spring25/06_StudyDesign.pdf) | [Design Lab](Labs_Spring25/Design_lab.html) | IMS Chapter 2 (pgs. 28-37) | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) [Homework 2](Homework_Spring25/Homework2.html) assigned Wed 2/12 and due Friday 2/21 at 10pm. -->
<!-- 2) [Tables Lab](Labs_Spring25/tables_and_descriptions_lab.html) due Wednesday 2/19 at 10pm. -->
<!-- 3) [Design Lab](Labs_Spring25/Design_lab.html) due Wednesday 2/19 at 10pm. -->
<!-- 4) Exam 1 will be Wednesday 2/26 during normal class time. Monday 2/24 will be a review day. -->

<!-- --- -->

<!-- ### Week 5 (Correlation and Regression) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 2/17 | Lab and Homework Day | - | - | -->
<!-- | Wed 2/19 | [Correlation](Lectures_Spring25/07_Correlation.pdf) | [Correlation and Regression Lab](Labs_Spring25/corr_regression_lab.html) | - | -->
<!-- | Fri 2/21 | [Linear Regression](Lectures_Spring25/08_LinearRegression.pdf) | [Correlation and Regression Lab](Labs_Spring25/corr_regression_lab.html) | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) [Homework 3](Homework_Spring25/Homework3.html) is due Friday 2/27 at 10pm. The HW is extremely similar to some exam questions. I recommend finishing this early. -->
<!-- 2) Exam 1 will be Wednesday 2/26 during normal class time. Monday 2/24 will be a review day. -->

<!-- --- -->

<!-- ### Week 6 (Exam 1) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 2/24 | Review Day | - | Optional: IMS Chapter 7.1 - 7.2.4 (pages 105-119, avoid strength of fit section) | -->
<!-- | Wed 2/26 | Exam 1 | - | - | -->
<!-- | Fri 2/28 | - | [dplyr Lab](Labs_Spring25/dplyr_lab.html) | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) [Regression Lab](Labs_Spring25/corr_regression_lab.html) due Monday 2/24 at 10pm. -->
<!-- 2) [dplyr Lab](Labs_Spring25/dplyr_lab.html) due Wednesday 3/05 at 10pm. -->

<!-- --- -->

<!-- ## Exam \#2 Content -->

<!-- ### Week 7 (Probability) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 3/03 | [Probability 1](Lectures_Spring25/Probability1.pdf) | [Probability Worksheet 1](Labs_Spring25/ProbWorksheet1.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections 3.1.1-3.1.4 and 3.1.6| -->
<!-- | Wed 3/05 | [Probability 2](Lectures_Spring25/Probability2.pdf) | [Probability Worksheet 2](Labs_Spring25/ProbWorksheet2.pdf) | [OpenIntro](https://www.biostat.jhsph.edu/~iruczins/teaching/books/2019.openintro.statistics.pdf) Sections 3.1.5 and 3.2.1-3.2.5 | -->
<!-- | Fri 3/07 | [Odds and Relative Risk](Lectures_Spring25/Odds_Risk.pdf) | [Probability Worksheet 3](Labs_Spring25/ProbWorksheet3.pdf) | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) [Homework 4](Homework_Spring25/Homework4.html) due Friday 3/28 at 10pm. -->

<!-- --- -->

<!-- ### Week 8\* (Normal Distributions) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 3/24 | [Expectation and Variance](Lectures_Spring25/Probability3_ExpVar.pdf) and [Normal Distributions](Lectures_Spring25/NormalDistribution.pdf) | [Normal Distribution Lab](Labs_Spring25/normaldist_probabilities_lab.html) | - | -->
<!-- | Wed 3/26 | [Sampling Distributions](Lectures_Spring25/SamplingDistributions.pdf) | [Normal Distribution Lab](Labs_Spring25/normaldist_probabilities_lab.html) cont'd | - | -->
<!-- | Fri 3/28 | [Confidence Intervals for a Population Mean](Lectures_Spring25/ConfidenceIntervals_PopMean.pdf) | [CI Lab 1](Labs_Spring25/confidence_intervals_1.html) | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) Probability Worksheets scanned and uploaded to gradescope by Wednesday 3/26 at 10pm. -->
<!-- 2) Normal Distribution Lab due Sunday 3/30 at 10pm. -->
<!-- 3) CI Lab 1 due Wednesday 4/02 at 10pm. -->

<!-- --- -->

<!-- ### Week 9 (Confidence Intervals) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 3/31 | [More on CIs](Lectures_Spring25/CI_tDist.pdf) and  [CIs for Difference in Means](Lectures_Spring25/CI_DiffMeans.pdf)| [CI Lab 1](Labs_Spring25/confidence_intervals_1.html) | - | -->
<!-- | Wed 4/02 | Homework and Lab Day | [CI Lab 1] cont'd | [CI for Means -- Quick Guide](CI_for_means_quickguide.html) | -->
<!-- | Fri 4/04 | [Confidence Intervals for Proportions](Lectures_Spring25/CI_proportions_209.pdf) | [CI Lab 2](Labs_Spring25/CI_Lab2.html) | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) Exam 2 on Friday 4/11 in normal class time.  -->
<!-- 2) CI Lab 1 due Friday 4/04 at 10pm. -->
<!-- 3) [HW5](Homework_Spring25/Homework5_209.html) due Friday 4/11 at 10pm. -->
<!-- 4) [HW6](Homework_Spring25/Homework6_209.html) due Friday 4/18 at 10pm. -->

<!-- --- -->

<!-- ### Week 10 (CIs and Exam) -->
<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 4/07 | [Bootstrapping](Lectures_Spring25/Bootstrapping.pdf) | [Bootstrapping Lab](Labs_Spring25/Bootstrapping_Lab.html) | [CI for Props. -- Quick Guide](CI_for_props_quickguide.html) | -->
<!-- | Wed 4/09 | Review Day | - | - | -->
<!-- | Fri 4/11 | Exam 2  | - | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) CI Lab 2 due Tuesday 4/08 at 10pm. -->
<!-- 2) Bootstrapping Lab due Wednesday 4/09 at 10pm. -->
<!-- 3) [Project Info](Exams_Spring25/STA209_project.html) -->

<!-- --- -->

<!-- ### Week 11 (Hypothesis Testing) -->

<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 4/14 | [Hypothesis Testing 1](Lectures_Spring25/HypothesisTesting1.pdf) | [Testing Worksheet (PDF)](Labs_Spring25/TestingWorksheet1.pdf) [Webpage Format](Labs_Spring25/TestingWorksheet1.html) | - | -->
<!-- | Wed 4/16 | Project and Worksheet Day | Worksheet 1 cont'd | - | -->
<!-- | Fri 4/18 | [HT - P-values and Test-stats](Lectures_Spring25/HypothesisTesting2.pdf) | [Testing Worksheet 2 (PDF)](Labs_Spring25/TestingWorksheet2.pdf) [Webpage Format](Labs_Spring25/TestingWorksheet2.html) | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) Project groups due Wednesday night at 10pm. -->
<!-- 2) Testing Worksheet 1 due Friday 4/18 at 10pm. -->
<!-- 3) Testing Worksheet 2 due Monday 4/21 at 10pm. -->

<!-- --- -->

<!-- ### Week 12 (Hypothesis Test cont'd) -->

<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 4/21 | [HT - Props and Means](Lectures_Spring25/HypothesisTesting3.pdf) and [HT - More on Differences](Lectures_Spring25/HypothesisTesting4.pdf) | [Testing Worksheet 3 (PDF)](Labs_Spring25/TestingWorksheet3.pdf) [Webpage Format](Labs_Spring25/TestingWorksheet3.html) | - | -->
<!-- | Wed 4/23 | [HT - Decision Making](Lectures_Spring25/HypothesisTesting5.pdf)  | [Testing Worksheet 4 (PDF)](Labs_Spring25/TestingWorksheet4.pdf) [Webpage Format](Labs_Spring25/TestingWorksheet4.html) | [ASA Statement on P-values](https://www.amstat.org/asa/files/pdfs/p-valuestatement.pdf) | -->
<!-- | Fri 4/25 | [Chi Square Tests (GoF)](Lectures_Spring25/Chi2Test.pdf) | [Testing Lab](Labs_Spring25/HypothesisTestingLab.html) | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) Testing Worksheet 3 due Friday 4/25 at 10pm. -->
<!-- 2) Project proposal due Friday 4/25 at 10pm (gradescope link will be posted). -->
<!-- 3) Testing Worksheet 4 will take the place of HW7 due Friday 5/2 at 10pm. -->
<!-- 4) [Exam 2 corrections](Exams_Spring25/exam2_corrections.pdf) will be posted on Gradescope and due Friday 5/2 at 10pm. Potentiality for half credit earned back for missed questions (available to all). -->

<!-- --- -->

<!-- ### Week 13 (Chi-square and ANOVA) -->

<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 4/28 | [Chi Square Tests (Ind.)](Lectures_Spring25/Chi2_Independence.pdf) | [Testing Lab](Labs_Spring25/HypothesisTestingLab.html) cont'd | - | -->
<!-- | Wed 4/30 | [ANOVA 1](Lectures_Spring25/Anova1.pdf) | [ANOVA Lab](Labs_Spring25/ANOVA_lab.html) Q1+2 | - | -->
<!-- | Fri 5/02 | [ANOVA 2](Lectures_Spring25/Anova2.pdf) | [ANOVA Lab](Labs_Spring25/ANOVA_lab.html) Q3+ | - | -->

<!-- **Assignments and Deadlines** -->

<!-- 1) Testing Lab due Friday 5/02 at 10pm. We won't have extra time to work on it Wednesday. -->
<!-- 2) Anova Lab due Sunday 5/04 at 10pm. -->
<!-- 3) Project exploratory analysis due Friday 5/09 at 10pm. -->

<!-- [Project Writeup Example](Exams_Spring25/final_writeup.pdf) courtesy of Professor Nolte. -->

<!-- --- -->

<!-- ### Week 14 (Finishing Up) -->

<!-- | Date | Lecture | Lab | Reading | -->
<!-- |:-----|:-------|:-----|:-----| -->
<!-- | Mon 5/05 | [ANOVA - SLR](Lectures_Spring25/ANOVA_SLR.pdf)  | [ANOVA Regression Lab](Labs_Spring25/ANOVA_regression_lab.html) Q1 | - | -->
<!-- | Wed 5/07 | [ANOVA - MLR](Lectures_Spring25/ANOVA_MLR.pdf) | [ANOVA Regression Lab](Labs_Spring25/ANOVA_regression_lab.html) Q2+3 | - | -->
<!-- | Fri 5/09 | [Regression Errors](Lectures_Spring25/Regression_Error.pdf) | [ANOVA Regression Lab](Labs_Spring25/ANOVA_regression_lab.html) Q4+5 | - | -->

<!-- *Bonus*: [AI and Machine Learning Overview](Lectures_Spring25/AI_ML.pdf) -->

<!-- **Assignments and Deadlines** -->

<!-- 1) Project exploratory analysis due Friday 5/09 at 10pm. -->
<!-- 2) [ANOVA Regression Lab](Labs_Spring25/ANOVA_regression_lab.html) due Monday 5/12 at 10pm (solutions will be posted ahead of time). -->


<!-- --- -->


<!-- ## Exam 1 Info -->

<!-- Exam 1 will be in-class Wednesday Feb. 26. -->

<!-- [Exam 1 Topics Outline](Exams_Spring25/topic_list_exam1.html) -->

<!-- [Practice Exam 1](Exams_Spring25/practice_exam1.html) file and ([PDF Format](Exams_Spring25/practice_exam1.pdf)) -->

<!-- --- -->

<!-- ## Exam 2 Info -->

<!-- Exam 2 will be in-class Friday 4/11. -->

<!-- [Exam 2 Topics Outline](Exams_Spring25/topic_list_exam2_209.html) -->

<!-- [Practice Exam 2](Exams_Spring25/practice_exam2.html) -->

<!-- [Formula Sheet](Exams_Spring25/exam2_formulas.pdf) -->

<!-- --- -->

<!-- ### Exam 3 Info -->

<!-- [Exam 3 Topics List](exams/topic_list_exam3_209.pdf) -->

<!-- [Short Answer Practice](exams/Exam3_shortanswer_209.html) -->

<!-- [Methods Review](exams/STA209_methodsreview.pdf) and [(Solution)](Exams_Spring25/Methods_review_solutions.html) -->

<!-- [Practice Exam 1](exams/exam3_practice1_209.pdf) and [(Solutions)](Exams_Spring25/exam3_practice1_209_solutions.pdf) and [(Question4)](Exams_Spring25/exam3_practice1_Q4.html) -->

<!-- [Practice Exam 2](exams/practice_exam3.pdf) and [(Solutions)](Exams_Spring25/practice_exam3_solutions.pdf) -->

<!-- [Formula Sheet](exams/exam3_formulas209.pdf) -->

<!-- --- -->

<!-- ### Lab Solutions -->

<!-- [Intro R Lab](Labs_Spring25/01_introR_solutions.html) -->

<!-- [Data Viz Lab](Labs_Spring25/DataVisualizationLab_Solutions.html) -->

<!-- [Ggplot2 Lab](Labs_Spring25/ggplot_lab_solutions.html) -->

<!-- [Tables Lab](Labs_Spring25/tables_lab_solutions.html) -->

<!-- [Design Lab](Labs_Spring25/design_lab_solutions.html) -->

<!-- [Regression Lab](Labs_Spring25/corr_regression_lab_solutions.html) -->

<!-- [Normal Dist. Lab](Labs_Spring25/normaldist_probabilities_lab_sol.html) -->

<!-- [CI Lab 1](Labs_Spring25/confidence_intervals_1_sol.html) -->

<!-- [Probability "FunSheets"](Labs_Spring25/ProbWorksheets_Solutions.pdf) -->

<!-- [CI Lab 2](Labs_Spring25/CI_Lab2_sol.html) -->

<!-- [Testing Worksheet 1](Labs_Spring25/TestingWorksheet1_sol.html) -->

<!-- [Testing Worksheet 2](Labs_Spring25/TestingWorksheet2_sol.html) -->

<!-- [Testing Worksheet 3](Labs_Spring25/TestingWorksheet3_sol.html) -->

<!-- [Testing Worksheet 4](Labs_Spring25/TestingWorksheet4_sol.html) -->

<!-- [Testing Lab](Labs_Spring25/HypothesisTestingLab_sol.html) -->

<!-- [ANOVA Lab](Labs_Spring25/ANOVA_lab_sol.html) -->

<!-- [ANOVA Regression Lab](Labs_Spring25/ANOVA_regression_lab_solutions.html) -->

<!-- ### Selected HW Solutions -->

<!-- [Homework 2](Homework_Spring25/Homework2_solutions.pdf) -->