---
title: "Syllabus - STAT-209 (Fall 2025)"
author: "Nathan Friedrichsen"
date: "2025-8-25"
output:
  html_document: default
  pdf_document: default
---

<hr style="border: none; border-top: 5px solid black;">

**Instructor**:

* Nathan Friedrichsen, Noyce 2220, friedrichsen@grinnell.edu

**Class Meetings**:

* STA-209-03: Noyce 2402, MWF 1:00-2:20 PM

**Office Hours**:

This time is purposefully scheduled for you to drop in and ask any questions about the course. Please feel free to stop by. If the time doesn't work for you, message me and we can try to arrange something.

* Location: Noyce 2220
* Time: TBD

**Mentor Information**:

More info will be posted.

**Gradescope Course numbers**

* STA-209-03: 

<hr style="border: none; border-top: 5px solid black;">

**Course Description**:

This course covers the application of basic statistical methods such as graphics and summary statistics, basic statistical inference for one and two samples, linear regression, one- and two-way ANOVA, and categorical data analysis. Students will use statistical software to analyze data and conduct simulations. (You will learn all these terms throughout the semester\!)

**Texts**:

* [Introduction to Modern Statistics, 1st Edition](https://openintro-ims.netlify.app/) (Free online\!)

We will occasionally have readings or assignment questions taken from this source. All additional materials will be posted on the course website.

There may also be readings or links from other sources which will be provided as necessary.

<hr style="border: none; border-top: 5px solid black;">

### Aims and Objectives

This course aims to introduce students to the field of statistics, including its vocabulary and fundamental principles. The course will prepare students to read, recognize, interpret, and discuss statistical concepts and their use in scientific applications. The course will provide students an understanding of the role of statistics within the scientific method, and provide students the tools to use data to make informed conclusions.

#### Learning Objectives

After completing this course, students should be able to:

* Apply methods of exploration, visualization, and statistical analysis to data in order to illustrate key findings and make justifiable inferences using statistical software (R)
* Communicate the methods and results of statistical analyses succinctly and accurately in both writing and speaking to statistical and non-statistical audiences.
* Read, identify, and critique the statistical concepts and choices of data presentation used in various media publications (newspaper articles, reports, blogs, etc.)

<hr style="border: none; border-top: 5px solid black;">

### Grading

<hr style="border: 1px solid black;">
<table style="width:100%; border-collapse: collapse; text-align: center;">
  <tr>
    <th>A</th>
    <th>A–</th>
    <th>B+</th>
    <th>B</th>
    <th>B–</th>
    <th>C</th>
    <th>D</th>
  </tr>
  <tr>
    <td>93–100</td>
    <td>90–92</td>
    <td>87–89</td>
    <td>83–86</td>
    <td>80–82</td>
    <td>70-79</td>
    <td>60-69</td>
  </tr>
</table>
<hr style="border: 1px solid black;">

**Labs** \- 15%

In-class labs serve as an opportunity to practice content you will see in lectures, and prepare you for homeworks and exams. The labs contain embedded questions that you and your lab partner(s) will answer together. Some lab questions may be scored for accuracy with feedback given, but by and large labs will be scored for effort/completion. Missing questions or lack of effort for labs *will* result in lower scores.

**Individual Homework** \- 10%

Homework will be assigned at most once per week and will be due on Gradescope, submitted as a pdf, *generally* due 10pm on Fridays. Gradescope requires that you indicate which problems appear on which page (we will go over an example) – failure to do this will result in a 25% deduction of that homework’s final score.

I encourage you to work with other students or visit the Math Lab for help on homework questions, but you should clearly understand all your answers and your assignment should be entirely in your own words. The homework is intended primarily as an exercise to practice and develop your understanding and to assist in identifying weaknesses: you do yourself a disservice if you submit work that you do not fully understand. None of what is assigned will be "busy work."

If you engage in significant collaboration with classmates or tutors, you must explicitly acknowledge that person(s) on the top of your assignment (again, you are encouraged to collaborate, and I want to emphasize that there is no penalty for doing so).

**Required Readings** 10\%

At least three papers will be assigned during the course of the semester to read. They will not be overly long nor mathematically difficult to read. The goal of these papers is to help solidify the big picture understanding that I want you to walk away from the class with. A single paper will be assigned one to two weeks before a small quiz on it will be given in class. These quizzes will be closed notes/papers.

**Exams (3)** \- 50\% in total (16.67\% each)

There will be 2 midterms and a final exam. Each midterm will focus on a specific set of content, but because course topics are naturally cumulative there may be some questions involving earlier content. The 3 exams will each contribute 16.67\% towards your end-of-semester grade.

Exams will be announced at least two weeks in advance. Exams will be closed notes, but you will given a formula sheet and be permitted to bring a  a calculator (no cellphone use allowed). You will not be responsible for writing your own R code on exams, but you should expect to encounter output from R as well as the code that produced it during each exam.

Alternative exam arrangements need to be made at least one week in advance of the time you plan to take the exam; this includes taking the exam in a different location, or times going beyond the given class time. Alternative arrangements are not guaranteed unless proper notification is given.

After the first two exams are graded, I will allow students with scores below 90\% an opportunity for exam corrections. You can earn back half credit for any missed question by submitting a correct answer and explanation of why the original answer was incorrect (up to a maximum exam score of 90\%). Exam correction answers must be fully correct to receive back half credit for the respective question.


**Final Project** \- 15%

There will be an ongoing group project throughout the 2nd half of the semester. The project will include a few short progress reports before culminating in a short in-class presentation and a three (3) page written report in the last week of the semester. More details will be announced later.

<hr style="border: none; border-top: 5px solid black;">

### Policies

**Class Sessions**

The core component of our class meetings will be comprised of lectures and also working through hands-on labs in a paired programming environment. You will have the freedom to choose your partner, or work independently near someone that you can occasionally consult with. During labs it is essential that you and your partner(s) work together, making certain that each of you understand your work equally well.

Most labs will begin with a brief “preamble” section that we will go through together as class. The purpose of this section is to introduce the topic of the lab and ensure a smooth start to each class meeting.

**Attendance**

Because this course involves some amount of group work, absences impact not only yourself but also your classmates. That said, I understand that missing class is sometimes necessary. I will not take attendance directly, but know that lack of attendance will most likely affect grades for homework, labs, and exams. If you must miss class, it would be polite and civil to let your lab partner know about it ahead of time if possible.

Please note that if you are sick I do NOT want you in class. Please do not come to class. If you show up and are clearly demostrating sympotoms of being sick you will be asked to leave.

**Late Policy**

*Tokens* reflect that life inevitably rears its ugly head in some fashion and ruins your best-laid plans. You begin the course with 2 tokens. Tokens may be used for HW and Lab extensions (1 token = 2 extra days to turn in). Outside of accomodations and the use of these tokens, absolutely **NO** late homework or labs will be accepted. Homeworks or labs due shortly before exams will be exempt from token use as it delays posting of assignment solutions.

**Software**

Software is increasingly an essential component of statistics and will play a role in this course. We will primarily use `R`, an open-source statistical software program.

You are welcome to use your own personal laptop, or a Grinnell College laptop, during the course. `R` is freely available and you can download it and it’s UI companion, `R Studio`, here (note: `R` must be downloaded and installed before `R Studio`):

1. Download `R` from [http://www.r-project.org/](http://www.r-project.org/)  
2. Download `R Studio` from [http://www.rstudio.com/](http://www.rstudio.com/)

You may also work on a classroom computer, all of which will have `R` and `R Studio` pre-installed.

Finally, Grinnell hosts an online version of R Studio that you may use while on campus internet: https://rstudio.grinnell.edu/

**Academic Honesty**

At Grinnell College you are part of a conversation among scholars, professors, and students, one that helps sustain both the intellectual community here and the larger world of thinkers, researchers, and writers. The tests you take, the research you do, the writing you submit-all these are ways you participate in this conversation.

The College presumes that your work for any course is your own contribution to that scholarly conversation, and it expects you to take responsibility for that contribution. That is, you should strive to present ideas and data fairly and accurately, indicate what is your own work, and acknowledge what you have derived from others. This care permits other members of the community to trace the evolution of ideas and check claims for accuracy.

Failure to live up to this expectation constitutes academic dishonesty. Academic dishonesty is misrepresenting someone else’s intellectual effort as your own. Within the context of a course, it also can include misrepresenting your own work as produced for that class when in fact it was produced for some other purpose. A complete list of dishonest behaviors, as defined by Grinnell College, [can be found here](https://www.grinnell.edu/about/leadership/offices-services/academic-success-center/resources).

**Inclusive Classroom**

Grinnell College makes reasonable accommodations for students with documented disabilities. Students with disabilities partner with the Office of Disability Resources to make academic accommodation letters available to faculty via the accommodation portal: access.grinnell.edu. To help ensure that your access needs are met, I encourage individual students to approach me so we can have a discussion about your distinctive learning needs and accommodations within the context of this course. If you have not already worked with the Office of Disability Resources and believe you may require academic accommodations for this course, Disability Resources staff can be reached via email at access@grinnell.edu or by stopping by their offices in Steiner Hall.

**Religious Holidays**

Grinnell College encourages students who plan to observe holy days that coincide with class meetings or assignment due dates to consult with your instructor in the first three weeks of classes so that you may reach a mutual understanding of how you can meet the terms of your religious observance, and the requirements of the course.

**Pregnancy Related Conditions, Title IX**

Grinnell College is committed to compliance with Title IX and to supporting the academic success of pregnant and parenting students and students with pregnancy related conditions. If you are a pregnant student, have pregnancy related conditions, or are a parenting student (child under 1-year needs documented medical care) who wishes to request reasonable related supportive measures from the College under Title IX, please email the Title IX Coordinator at [titleix@grinnel.edu](mailto:titleix@grinnel.edu). The Title IX Coordinator will work with Disability Resources and your professors to provide reasonable supportive measures in support of your education while pregnant or as a parent under Title IX. 

<hr style="border: none; border-top: 5px solid black;">

### Misc

**Getting Help**

In addition to visiting office hours and completing the recommended readings, there are many other ways in which you can find help on assignments and projects.

The Data Science and Social Inquiry Lab (DASIL) is staffed by mentors who are experienced in R programming and may be able to troubleshoot coding problems you are having.

The Grinnell Math Lab is located on the 2nd floor of Noyce Science Center in Room 2012 and offers drop-in statistics tutoring.

The online platform Stack Overflow is a useful resource to find user-generated coding solutions to common R problems. Nearly all professionals have needed to “look up” a coding strategy on a site like Stack Overflow at some point in their career, and I have no problem with you doing the same on assignments or projects. However, if you make substantial use of a Stack Overflow answer (ie: actually integrating lines of code written by someone else into your work, not just getting help identifying the right functions/arguments) the expectation is that you cite or acknowledge doing so.

**Large Language Models and AI**

Grinnell’s college-wide Academic Honesty policy requires that use of generative AI be appropriately cited or acknowledged as any other source would be. In this course you are fully permitted to use generative AI for assistance on in-class work or homework assignments, so long as you properly acknowledge your use and work within the statistical and coding frameworks described in our lectures and labs. Using generative AI to produce solutions that are inconsistent with the approaches and methods discussed in our lectures and labs will result in low scores on assignments. Some particular cases where generative AI can be helpful in this course include: checking your written work for errors or typos, understanding coding error messages, and explaining example code in an a more interactive manner. If you decide to use generative AI to assist with in-class work or homework it is essential for you to recognize that you will not have access to these tools on in-class exams, which comprise the majority of your end-of-semester grade. Thus, it is critical that you use AI as a tool, not as a replacement for your own thinking and understanding of course topics.

*Note: My stance on LLM usage through the course may change, but you will be given notice and, if applied retroactively, won’t lower your grade*