---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# CI for a single population proportion (p)

### Conditions

1) The data comes from a random sample.
2) $n * \widehat{p} \geq 10$ (Success Condition)
3) $n * (1-\widehat{p}) \geq 10$ (Failure Condition)

**Note:** Success and Failure conditions count the \# of successes and \# of failures respectively.

### Formula

$\widehat{p} \pm z^* \times \sqrt{\frac{\widehat{p}(1-\widehat{p})}{n}}$

$z^*$ is the appropriate value from the normal distribution that gives us the Confidence \% that we want

- 95% Confidence → $z^*$ = 1.96
- 80% Confidence → $z^*$ = 1.282
- 90% Confidence → $z^*$ = 1.645
- 99% Confidence → $z^*$ = 2.576

--- 

# CI for a difference in population proportions ($p_1 - p_2$)

### Conditions

1) Data for both groups comes from a random sample.
2) $n_1 * \widehat{p}_1 \geq 10$ (Success Condition Grp 1)
3) $n_1 * (1-\widehat{p}_1) \geq 10$ (Failure Condition Grp 1)
2) $n_2 * \widehat{p}_2 \geq 10$ (Success Condition Grp 2)
3) $n_2 * (1-\widehat{p}_2) \geq 10$ (Failure Condition Grp 2)

**Note:** Success and Failure conditions count the \# of successes and \# of failures respectively.

### Formula

$(\widehat{p}_1 - \widehat{p}_2) \pm z^* \times \sqrt{\frac{\widehat{p}_1(1-\widehat{p}_1)}{n_1}+\frac{\widehat{p}_2(1-\widehat{p}_2)}{n_2}}$

$z^*$ is the appropriate value from the normal distribution that gives us the Confidence \% that we want

- 95% Confidence → $z^*$ = 1.96
- 80% Confidence → $z^*$ = 1.282
- 90% Confidence → $z^*$ = 1.645
- 99% Confidence → $z^*$ = 2.576

\newpage

# Confidence Interval for a Single Mean

### Conditions

1) The *population* is Normal **OR** the sample size $n \geq 30$
2) There was a random sample

### 95\% Confidence Interval Formula ($\sigma$ known)

### $\overline{x} \pm 1.96 \times \frac{\sigma}{\sqrt{n}}$

### 100(1-$\alpha$)\% Confidence Interval Formula ($\sigma$ known)

### $\overline{x} \pm z^* \times \frac{\sigma}{\sqrt{n}}$

value of $z^*$ determined by confidence level.

Common values of $z^*$:

- 95\% confidence $\rightarrow z^*$ = 1.96
- 80\% confidence $\rightarrow z^*$ = 1.28
- 90\% confidence $\rightarrow z^*$ = 1.64
- 99\% confidence $\rightarrow z^*$ = 2.58

### 100(1-$\alpha$)\% Confidence Interval Formula ($\sigma$ unknown)

### $\overline{x} \pm t_{(1-\alpha/2, df=n-1)} \times \frac{s}{\sqrt{n}}$

where $t_{(1-\alpha/2, df=n-1)}$ is the $1-\alpha/2$ quantile for a t-distribution with n-1 degrees of freedom (use `qt()` to get final values).

---

# Confidence Interval for Difference in Means

### Conditions

1) The *populations* are Normal **OR** the both sample sizes $n_1 \geq 30$ and $n_2 \geq 30$
2) There was a random sample for both groups.

### 100(1-$\alpha$)\% Confidence Interval Formula ($\sigma$ unknown)

### ($\overline{x}_1 - \overline{x}_2) \pm t_{(1-\alpha/2, df)} \times \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}$

where $t_{(1-\alpha/2, df)}$ is the $1-\alpha/2$ quantile for a t-distribution with degrees of freedom $df=min(n_1, n_2)-1$ (use `qt()` to get final values).